"""make interview candidate_id nullable

Revision ID: 55b6bd036239
Revises: a34a080a76a0
Create Date: 2026-03-02 23:39:02.959749
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b6bd036239'
down_revision: Union[str, None] = 'a34a080a76a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
