"""add_skills_matrix_models

Revision ID: b896be0cbc49
Revises: 55b6bd036239
Create Date: 2026-03-05 13:05:01.161972
"""
from typing import Sequence, Union

import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b896be0cbc49'
down_revision: Union[str, None] = '55b6bd036239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_capabilities_slug'), 'capabilities', ['slug'], unique=True)
    op.create_table('capability_levels',
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_levels_capability_id'), 'capability_levels', ['capability_id'], unique=False)
    op.create_table('role_templates',
    sa.Column('venture_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venture_id'], ['ventures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_templates_venture_id'), 'role_templates', ['venture_id'], unique=False)
    op.create_table('role_capability_requirements',
    sa.Column('role_template_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_template_id'], ['role_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_capability_requirements_capability_id'), 'role_capability_requirements', ['capability_id'], unique=False)
    op.create_index(op.f('ix_role_capability_requirements_role_template_id'), 'role_capability_requirements', ['role_template_id'], unique=False)
    op.add_column('candidates', sa.Column('role_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'role_templates', ['role_template_id'], ['id'])
    op.add_column('rubric_criteria', sa.Column('capability_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'rubric_criteria', 'capabilities', ['capability_id'], ['id'])

    # --- Seed: 7 engineering capabilities with proficiency levels 1-5 ---
    capabilities_table = sa.table(
        'capabilities',
        sa.column('id', sa.UUID),
        sa.column('name', sa.String),
        sa.column('slug', sa.String),
        sa.column('description', sa.Text),
        sa.column('icon', sa.String),
        sa.column('order', sa.Integer),
    )
    levels_table = sa.table(
        'capability_levels',
        sa.column('id', sa.UUID),
        sa.column('capability_id', sa.UUID),
        sa.column('level', sa.Integer),
        sa.column('title', sa.String),
        sa.column('description', sa.Text),
    )

    CAPS = [
        {
            "id": uuid.UUID("a0000001-0000-0000-0000-000000000001"),
            "name": "Frontend Development",
            "slug": "frontend",
            "description": "UI/UX implementation, component architecture, state management, and browser technologies.",
            "icon": "monitor",
            "order": 1,
            "levels": [
                (1, "Foundational", "HTML/CSS basics. Can modify existing React components with guidance."),
                (2, "Developing", "Builds simple features independently. Understands component lifecycle and basic state management."),
                (3, "Proficient", "Designs component architecture. Implements complex state management (Zustand/Redux). Performance optimization."),
                (4, "Advanced", "Leads frontend architecture decisions. Design system creation. Advanced patterns (SSR, micro-frontends)."),
                (5, "Expert", "Sets industry-level standards. Contributes to framework ecosystems. Mentors across teams."),
            ],
        },
        {
            "id": uuid.UUID("a0000001-0000-0000-0000-000000000002"),
            "name": "Backend Development",
            "slug": "backend",
            "description": "API design, server architecture, database integration, and service patterns.",
            "icon": "server",
            "order": 2,
            "levels": [
                (1, "Foundational", "Understands REST basics. Can write simple CRUD endpoints with guidance."),
                (2, "Developing", "Builds APIs independently. Basic error handling, validation, and database queries."),
                (3, "Proficient", "Designs service architecture. Implements authentication, caching, async processing. Writes efficient queries."),
                (4, "Advanced", "Leads system design. Distributed systems patterns. Event-driven architecture. Performance tuning."),
                (5, "Expert", "Defines platform architecture. Designs systems at scale. Cross-team technical leadership."),
            ],
        },
        {
            "id": uuid.UUID("a0000001-0000-0000-0000-000000000003"),
            "name": "Data Engineering",
            "slug": "data-engineering",
            "description": "Data pipelines, ETL/ELT, data warehousing, streaming, and data infrastructure.",
            "icon": "database",
            "order": 3,
            "levels": [
                (1, "Foundational", "SQL basics. Understands tables, joins, and simple aggregations."),
                (2, "Developing", "Writes ETL scripts. Basic pipeline construction with existing tools (Airflow, dbt)."),
                (3, "Proficient", "Designs data pipelines end-to-end. Data modeling. Handles schema evolution and data quality."),
                (4, "Advanced", "Architects data platform. Real-time streaming. Optimizes at scale (partitioning, indexing strategies)."),
                (5, "Expert", "Defines data strategy across organization. Innovates data infrastructure patterns."),
            ],
        },
        {
            "id": uuid.UUID("a0000001-0000-0000-0000-000000000004"),
            "name": "Data Science & ML",
            "slug": "data-science-ml",
            "description": "Statistical analysis, machine learning, model development, and AI systems.",
            "icon": "brain",
            "order": 4,
            "levels": [
                (1, "Foundational", "Basic statistics. Can run pre-built models and interpret outputs."),
                (2, "Developing", "Implements standard ML algorithms. Feature engineering. Basic model evaluation."),
                (3, "Proficient", "Designs ML pipelines. Model selection and hyperparameter tuning. Production deployment with MLOps."),
                (4, "Advanced", "Architects ML systems. Novel approaches. Handles edge cases at scale. LLM integration patterns."),
                (5, "Expert", "Pushes state-of-the-art. Publishes research. Defines ML strategy for the organization."),
            ],
        },
        {
            "id": uuid.UUID("a0000001-0000-0000-0000-000000000005"),
            "name": "Analytics & BI",
            "slug": "analytics",
            "description": "Business intelligence, data visualization, metrics design, and analytical thinking.",
            "icon": "bar-chart-3",
            "order": 5,
            "levels": [
                (1, "Foundational", "Creates basic charts and dashboards. Understands common metrics (conversion, retention)."),
                (2, "Developing", "Designs dashboards independently. Writes analytical SQL. Identifies trends in data."),
                (3, "Proficient", "Defines KPI frameworks. A/B testing design. Advanced visualization. Stakeholder communication."),
                (4, "Advanced", "Builds analytics strategy. Self-service BI platforms. Predictive analytics integration."),
                (5, "Expert", "Defines data-driven culture. Cross-functional analytics leadership. Innovation in measurement."),
            ],
        },
        {
            "id": uuid.UUID("a0000001-0000-0000-0000-000000000006"),
            "name": "DevOps & Infrastructure",
            "slug": "devops",
            "description": "CI/CD, cloud infrastructure, containerization, monitoring, and reliability engineering.",
            "icon": "cloud",
            "order": 6,
            "levels": [
                (1, "Foundational", "Uses Docker basics. Understands CI/CD concepts. Can deploy with existing pipelines."),
                (2, "Developing", "Writes Dockerfiles and CI configs. Basic cloud resource management (GCP/AWS)."),
                (3, "Proficient", "Designs CI/CD pipelines. IaC (Terraform/Pulumi). Monitoring and alerting setup. Cost optimization."),
                (4, "Advanced", "Architects cloud infrastructure. Multi-region deployments. SRE practices. Platform engineering."),
                (5, "Expert", "Defines infrastructure strategy. Innovates deployment patterns. Cross-org platform leadership."),
            ],
        },
        {
            "id": uuid.UUID("a0000001-0000-0000-0000-000000000007"),
            "name": "Technical Leadership",
            "slug": "leadership",
            "description": "Architecture decisions, team mentorship, technical strategy, and cross-team collaboration.",
            "icon": "users",
            "order": 7,
            "levels": [
                (1, "Foundational", "Participates constructively in code reviews. Asks good questions. Documents own work."),
                (2, "Developing", "Mentors junior developers. Contributes to architecture discussions. Leads small features."),
                (3, "Proficient", "Drives technical decisions for a team. Effective code review leadership. Cross-team collaboration."),
                (4, "Advanced", "Sets technical direction for multiple teams. Influences engineering culture. Resolves complex tradeoffs."),
                (5, "Expert", "Defines engineering vision. Industry thought leadership. Organizational-level technical strategy."),
            ],
        },
    ]

    for cap in CAPS:
        cap_id = cap["id"]
        op.bulk_insert(capabilities_table, [{
            "id": cap_id,
            "name": cap["name"],
            "slug": cap["slug"],
            "description": cap["description"],
            "icon": cap["icon"],
            "order": cap["order"],
        }])
        level_rows = []
        for level, title, desc in cap["levels"]:
            level_rows.append({
                "id": uuid.uuid4(),
                "capability_id": cap_id,
                "level": level,
                "title": title,
                "description": desc,
            })
        op.bulk_insert(levels_table, level_rows)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rubric_criteria', type_='foreignkey')
    op.drop_column('rubric_criteria', 'capability_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'role_template_id')
    op.drop_index(op.f('ix_role_capability_requirements_role_template_id'), table_name='role_capability_requirements')
    op.drop_index(op.f('ix_role_capability_requirements_capability_id'), table_name='role_capability_requirements')
    op.drop_table('role_capability_requirements')
    op.drop_index(op.f('ix_role_templates_venture_id'), table_name='role_templates')
    op.drop_table('role_templates')
    op.drop_index(op.f('ix_capability_levels_capability_id'), table_name='capability_levels')
    op.drop_table('capability_levels')
    op.drop_index(op.f('ix_capabilities_slug'), table_name='capabilities')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
