"""add_technology_stacks

Revision ID: eb65518f4fe1
Revises: b896be0cbc49
Create Date: 2026-03-05 13:43:18.635173
"""
from typing import Sequence, Union

import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb65518f4fe1'
down_revision: Union[str, None] = 'b896be0cbc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_capability_id'), 'technologies', ['capability_id'], unique=False)
    op.create_index(op.f('ix_technologies_slug'), 'technologies', ['slug'], unique=True)
    op.create_table('role_technology_requirements',
    sa.Column('role_template_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_template_id'], ['role_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_template_id', 'technology_id', name='uq_role_tech_req')
    )
    op.create_index(op.f('ix_role_technology_requirements_role_template_id'), 'role_technology_requirements', ['role_template_id'], unique=False)
    op.create_index(op.f('ix_role_technology_requirements_technology_id'), 'role_technology_requirements', ['technology_id'], unique=False)

    # --- Seed: ~82 technologies across 7 capabilities ---
    tech_table = sa.table(
        'technologies',
        sa.column('id', sa.UUID),
        sa.column('capability_id', sa.UUID),
        sa.column('name', sa.String),
        sa.column('slug', sa.String),
        sa.column('icon', sa.String),
        sa.column('order', sa.Integer),
    )

    # Capability UUIDs (from previous migration)
    CAP_FRONTEND = uuid.UUID("a0000001-0000-0000-0000-000000000001")
    CAP_BACKEND = uuid.UUID("a0000001-0000-0000-0000-000000000002")
    CAP_DATA_ENG = uuid.UUID("a0000001-0000-0000-0000-000000000003")
    CAP_DATA_SCI = uuid.UUID("a0000001-0000-0000-0000-000000000004")
    CAP_ANALYTICS = uuid.UUID("a0000001-0000-0000-0000-000000000005")
    CAP_DEVOPS = uuid.UUID("a0000001-0000-0000-0000-000000000006")
    CAP_LEADERSHIP = uuid.UUID("a0000001-0000-0000-0000-000000000007")

    TECHS = {
        CAP_FRONTEND: [
            ("React", "react"),
            ("Vue.js", "vuejs"),
            ("Angular", "angular"),
            ("Svelte", "svelte"),
            ("Next.js", "nextjs"),
            ("TypeScript", "typescript"),
            ("Tailwind CSS", "tailwindcss"),
            ("HTML/CSS", "html-css"),
            ("Webpack/Vite", "webpack-vite"),
            ("Storybook", "storybook"),
            ("React Native", "react-native"),
            ("Cypress/Playwright", "cypress-playwright"),
        ],
        CAP_BACKEND: [
            ("Python", "python"),
            ("Node.js", "nodejs"),
            ("Go", "go"),
            ("Java", "java"),
            ("Rust", "rust"),
            ("FastAPI", "fastapi"),
            ("Django", "django"),
            ("Express.js", "expressjs"),
            ("GraphQL", "graphql"),
            ("gRPC", "grpc"),
            ("Redis", "redis"),
            ("RabbitMQ/Kafka", "rabbitmq-kafka"),
        ],
        CAP_DATA_ENG: [
            ("PostgreSQL", "postgresql"),
            ("MySQL", "mysql"),
            ("MongoDB", "mongodb"),
            ("Apache Spark", "apache-spark"),
            ("Apache Airflow", "apache-airflow"),
            ("dbt", "dbt"),
            ("Snowflake", "snowflake"),
            ("BigQuery", "bigquery"),
            ("Apache Kafka", "apache-kafka"),
            ("Elasticsearch", "elasticsearch"),
            ("Delta Lake", "delta-lake"),
            ("Apache Flink", "apache-flink"),
        ],
        CAP_DATA_SCI: [
            ("TensorFlow", "tensorflow"),
            ("PyTorch", "pytorch"),
            ("scikit-learn", "scikit-learn"),
            ("Pandas/NumPy", "pandas-numpy"),
            ("Jupyter", "jupyter"),
            ("MLflow", "mlflow"),
            ("Hugging Face", "huggingface"),
            ("LangChain", "langchain"),
            ("OpenAI API", "openai-api"),
            ("Ray", "ray"),
            ("Spark MLlib", "spark-mllib"),
            ("Weights & Biases", "wandb"),
        ],
        CAP_ANALYTICS: [
            ("SQL", "sql-analytics"),
            ("Looker", "looker"),
            ("Tableau", "tableau"),
            ("Power BI", "power-bi"),
            ("Metabase", "metabase"),
            ("Google Analytics", "google-analytics"),
            ("Amplitude", "amplitude"),
            ("Mixpanel", "mixpanel"),
            ("R", "r-lang"),
            ("Excel/Sheets", "excel-sheets"),
        ],
        CAP_DEVOPS: [
            ("Docker", "docker"),
            ("Kubernetes", "kubernetes"),
            ("Terraform", "terraform"),
            ("AWS", "aws"),
            ("GCP", "gcp"),
            ("Azure", "azure"),
            ("GitHub Actions", "github-actions"),
            ("Jenkins", "jenkins"),
            ("Prometheus/Grafana", "prometheus-grafana"),
            ("Datadog", "datadog"),
            ("Ansible", "ansible"),
            ("Pulumi", "pulumi"),
        ],
        CAP_LEADERSHIP: [
            ("Architecture Design", "architecture-design"),
            ("System Design", "system-design"),
            ("Code Review", "code-review"),
            ("RFC/ADR Writing", "rfc-adr-writing"),
            ("Agile/Scrum", "agile-scrum"),
            ("OKR Planning", "okr-planning"),
            ("Technical Mentoring", "technical-mentoring"),
            ("Incident Management", "incident-management"),
            ("Stakeholder Communication", "stakeholder-communication"),
            ("Cross-Team Coordination", "cross-team-coordination"),
        ],
    }

    rows = []
    for cap_id, techs in TECHS.items():
        for idx, (name, slug) in enumerate(techs):
            rows.append({
                "id": uuid.uuid4(),
                "capability_id": cap_id,
                "name": name,
                "slug": slug,
                "icon": None,
                "order": idx + 1,
            })

    op.bulk_insert(tech_table, rows)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_technology_requirements_technology_id'), table_name='role_technology_requirements')
    op.drop_index(op.f('ix_role_technology_requirements_role_template_id'), table_name='role_technology_requirements')
    op.drop_table('role_technology_requirements')
    op.drop_index(op.f('ix_technologies_slug'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_capability_id'), table_name='technologies')
    op.drop_table('technologies')
    # ### end Alembic commands ###
